### PR TITLE
sysctl: Add job level kernel parameters and modules

### PR DESCRIPTION
**Pull request by giner**
**Background**

Issue: Some of bosh releases require kernel tuning to work properly, e.g. routing, diego and more (see https://github.com/cloudfoundry/routing-release/issues/138 for more context). There's no a unified way of changing kernel parameters so every release does it in its own way which leads to a number of issues such as accidental override of parameters by a different job running on the same vm or having parameter not applied at all.

This PR is an attempt to solve the issue by providing a common way of specifying kernel parameters to bosh release maintainers by simply adding sysctl.conf file to the releases. When applying the settings **will be checked for conflicted values**. If a release require a **kernel module to be loaded** before applying kernel parameters, this can be done by adding a module name (with options if required) to modules.conf.

**How this works**
1. Load modules from job config
    1. Read all of /var/vcap/jobs/*/config/os-conf/modules.conf if any
    2. Parse, check for conflicts (same modules having different options) and exit with an error if any
    3. Write list of modules to /etc/modules-load.d/bosh-os-conf-modules.conf and module options to /etc/modprobe.d/bosh-os-conf-module-options.conf
    4. Load modules by restarting /etc/init.d/kmod
2. Apply kernel parameters from job config and instance group level overrides
    1. Read all of /var/vcap/jobs/*/config/os-conf/sysctl.conf if any
    2. Parse, check for conflicts (same parameters having different values) and exit with an error if any
    3. Write parsed parameters with their values to a file under /etc/sysctl.d/
    4. Add instance group level overrides
    5. Apply by running `sysctl --system`

### CODE REVIEW

**Comment by giner** [comment]
The same can be done for modules (will be added to the same pre-start script to make sure that modules are loaded before sysctl parameters are applied).

**Comment by giner** [comment]
Added modules.conf

**Comment by giner** [comment]
Proposal: [link](https://lists.cloudfoundry.org/g/cf-bosh/topic/31805026?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,31805026)

**Comment by aashah** [comment]
Hey @giner,

When the team originally got this PR, there was definitely some hesitancy as it was a breaking change, and requires a lot of deep knowledge of co-located jobs. This led us to collectively trying to gather feedback in an experimental way. Unfortunately there was no feedback...

This leads us to believe this change might be risky since it might break people unknowingly. We're also now falling back to some of that original hesitancy.

The natural step after this is to simply move this into a release that is managed by you.

On a separate note, we're really sorry that this took such an immense amount of time. I think this is largely due to us trying to get feedback via that RFC process. In hindsight, we probably would not approach similar situations with an RFC.

- Aakash & @jaresty

**Comment by giner** [comment]
Hi @aakash, hi @jaresty,

I don't have any personal attachment to this PR, no worries. At the same time I want to note that the original problem is not solved and it's likely to hit again in different ways (release maintainers of capi and diego know it, cf operators know it, may be others do too). As you can guess there is not much value in maintaining this change separately as the most valuable outcome would be stable and predictable behavior of cf-deployment over time and in different environments. The suggested change is not the only way to solve the issue however it seems that noone plans to take the lead, put things together and have it done.

**Pull request closed without merging**
